name: build and deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Build
        run: hugo --minify
      
      - name: Deploy
        run: |
          mkdir ~/.ssh
          echo "$ssh_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          ssh pa2sh.club 'mkdir -p ~/pa2sh'
          rsync -avz -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" configutarion.nix pa2sh@pa2sh.club:/home/pa2sh/pa2sh/configuration.nix
          rsync -avz -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" public/ pa2sh@pa2sh.club:/home/pa2sh/pa2sh/public
          ssh pa2sh.club 'cd pa2sh && sudo nixos-rebuild switch'
        env:
          ssh_key: ${{ secrets.SSH_KEY }}